config/routes.rb
Rails.application.routes.draw do
  	
  resources :dependecies
  resources :permission_roles
  resources :requests
  resources :states
  resources :typerequests
  resources :usuarios
  devise_for :users
  resources :permissions
  resources :roles
  	root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dependecy.rb
class Dependecy < ApplicationRecord
	audited
end

app/models/permission.rb
class Permission < ApplicationRecord
	audited
end

app/models/permission_role.rb
class PermissionRole < ApplicationRecord
  belongs_to :permissions
  belongs_to :role
  audited
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :typerequest
  belongs_to :state
  audited
  attribute :state_id, :integer, default: '1'

  has_attached_file :cover
  validates_attachment_content_type :cover, content_type: [
	"application/pdf", "application/msword", 
	"application/vnd.openxmlformats-officedocument.wordprocessingml.document", 
	"application/vnd.oasis.opendocument.text",
	"application/vnd.ms-excel",
	"application/vnd.ms-office",
	"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	"application/vnd.oasis.opendocument.spreadsheet"
   ]
end

app/models/role.rb
class Role < ApplicationRecord
	audited
end

app/models/state.rb
class State < ApplicationRecord
	audited
end

app/models/typerequest.rb
class Typerequest < ApplicationRecord
	audited
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  audited
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  belongs_to :user
  belongs_to :role
  audited
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:nombre, :descripcion, :dependencie_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dependecies_helper.rb
module DependeciesHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/typerequests_helper.rb
module TyperequestsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render "partials/head" %>

  <body>
    <div id="container">
    <%= render "partials/navigation" %>
    
        <%= yield %>
      
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
      </div>
  </body>
</html>

app/views/partials/_contenedor.html.erb
            <!--Cabecera intro-->
            
               <!--Servicios Destacados-->
        <div class="container">
            
               <div class="holder_content">
               
        
                <section>
                 <ul>
                    <li>
                      <button class="btn-lg btn-default">
                      <%= link_to "Solicitar PQRS",new_request_path %>
                      </button>
                      
                      <button class="btn-lg btn-default">
                      <%= link_to "Consultar PRQS"," " %>
                       </button>
                    </li>
                  
                </ul>
            	</section>
           
               </div>
            
        </div>
               <!--end holder-->

app/views/partials/_head.html.erb
<head>
    <title>Empresa ABC</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/partials/_intro-log.html.erb
<div id="intro">
								
	<header class="group_bannner_left">
							   				<ul class="list-group">
								  			  <li class="list-group-item"><%= link_to 'Roles', roles_path %></li>
											  <li class="list-group-item"><%= link_to 'Permisos', permissions_path %></li> 
											  <li class="list-group-item"><%= link_to 'Empleados', usuarios_path %></li> 
											  <li class="list-group-item"><%= link_to 'Solicitudes de PQRS', requests_path %></li> 
											</ul> 
							   		
							   		</header>
						   		</div>

app/views/partials/_intro.html.erb
<div id="intro">
      
   		<div class="group_bannner_right">
   			<%= image_tag "slide.jpg", :size=>"550x316", :alt=>" " %>
   		</div>	
           
   		<header class="group_bannner_left">
   			<hgroup>
   				<h1>Empresa ABC</h1>
   				<h2>Santa marta - Magdalena</h2>
   			</hgroup>
   		</header>
   		</div>

   </div>
    

app/views/partials/_navigation.html.erb
<div = "container"	>	<!-- Logo -->
	 <%=link_to (image_tag "logo.png", :size=>"120x100", :alt=>"logo") %>

		<nav>
    		<ul>

    			<li><%= link_to "Inicio",  root_path %></li>
    			<li><%= link_to "¿Quiénes Somos?", " " %></li>
				<% if user_signed_in? %>
		            <li class="col-md">
		              <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete %>
		            </li>
		         <%else%>
				  	<li><%= link_to "Iniciar Sesion", user_session_path %></li>
		         <%end%>


    		</ul>
    	<!-- Final Navegacion -->
    	</nav>
			
		