config/routes.rb
Rails.application.routes.draw do
  	
  resources :dependecies
  resources :permission_roles
  resources :requests
  resources :states
  resources :typerequests
  resources :usuarios
  devise_for :users
  resources :permissions
  resources :roles
  	root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dependecy.rb
class Dependecy < ApplicationRecord
	audited
end

app/models/permission.rb
class Permission < ApplicationRecord
	audited
end

app/models/permission_role.rb
class PermissionRole < ApplicationRecord
  belongs_to :permissions
  belongs_to :role
  audited
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :typerequest
  belongs_to :state
  audited
  attribute :state_id, :integer, default: '1'

  has_attached_file :cover
  validates_attachment_content_type :cover, content_type: [
	"application/pdf", "application/msword", 
	"application/vnd.openxmlformats-officedocument.wordprocessingml.document", 
	"application/vnd.oasis.opendocument.text",
	"application/vnd.ms-excel",
	"application/vnd.ms-office",
	"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	"application/vnd.oasis.opendocument.spreadsheet"
   ]
end

app/models/role.rb
class Role < ApplicationRecord
	audited
end

app/models/state.rb
class State < ApplicationRecord
	audited
end

app/models/typerequest.rb
class Typerequest < ApplicationRecord
	audited
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  audited
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  belongs_to :user
  belongs_to :role
  audited
end

app/controllers/permission_roles_controller.rb
class PermissionRolesController < ApplicationController
  before_action :set_permission_role, only: [:show, :edit, :update, :destroy]

  # GET /permission_roles
  # GET /permission_roles.json
  def index
    @permission_roles = PermissionRole.all
  end

  # GET /permission_roles/1
  # GET /permission_roles/1.json
  def show
  end

  # GET /permission_roles/new
  def new
    @permission_role = PermissionRole.new
  end

  # GET /permission_roles/1/edit
  def edit
  end

  # POST /permission_roles
  # POST /permission_roles.json
  def create
    @permission_role = PermissionRole.new(permission_role_params)

    respond_to do |format|
      if @permission_role.save
        format.html { redirect_to @permission_role, notice: 'Permission role was successfully created.' }
        format.json { render :show, status: :created, location: @permission_role }
      else
        format.html { render :new }
        format.json { render json: @permission_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permission_roles/1
  # PATCH/PUT /permission_roles/1.json
  def update
    respond_to do |format|
      if @permission_role.update(permission_role_params)
        format.html { redirect_to @permission_role, notice: 'Permission role was successfully updated.' }
        format.json { render :show, status: :ok, location: @permission_role }
      else
        format.html { render :edit }
        format.json { render json: @permission_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permission_roles/1
  # DELETE /permission_roles/1.json
  def destroy
    @permission_role.destroy
    respond_to do |format|
      format.html { redirect_to permission_roles_url, notice: 'Permission role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permission_role
      @permission_role = PermissionRole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permission_role_params
      params.require(:permission_role).permit(:permissions_id, :role_id)
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:nombre, :descripcion, :dependencie_id)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:nombre, :descripcion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dependecies_helper.rb
module DependeciesHelper
end

app/helpers/permission_roles_helper.rb
module PermissionRolesHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/typerequests_helper.rb
module TyperequestsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/permission_roles/_form.html.erb
<%= form_with(model: permission_role, local: true) do |form| %>
  <% if permission_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(permission_role.errors.count, "error") %> prohibited this permission_role from being saved:</h2>

      <ul>
      <% permission_role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :permissions_id %>
    <%= form.text_field :permissions_id %>
  </div>

  <div class="field">
    <%= form.label :role_id %>
    <%= form.text_field :role_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/permission_roles/edit.html.erb
<h1>Editing Permission Role</h1>

<%= render 'form', permission_role: @permission_role %>

<%= link_to 'Show', @permission_role %> |
<%= link_to 'Back', permission_roles_path %>

app/views/permission_roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Permission Roles</h1>

<table>
  <thead>
    <tr>
      <th>Permissions</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @permission_roles.each do |permission_role| %>
      <tr>
        <td><%= permission_role.permissions %></td>
        <td><%= permission_role.role %></td>
        <td><%= link_to 'Show', permission_role %></td>
        <td><%= link_to 'Edit', edit_permission_role_path(permission_role) %></td>
        <td><%= link_to 'Destroy', permission_role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Permission Role', new_permission_role_path %>

app/views/permission_roles/new.html.erb
<h1>New Permission Role</h1>

<%= render 'form', permission_role: @permission_role %>

<%= link_to 'Back', permission_roles_path %>

app/views/permission_roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Permissions:</strong>
  <%= @permission_role.permissions %>
</p>

<p>
  <strong>Role:</strong>
  <%= @permission_role.role %>
</p>

<%= link_to 'Edit', edit_permission_role_path(@permission_role) %> |
<%= link_to 'Back', permission_roles_path %>