config/routes.rb
Rails.application.routes.draw do
  	
  resources :dependecies
  resources :permission_roles
  resources :requests
  resources :states
  resources :typerequests
  resources :usuarios
  devise_for :users
  resources :permissions
  resources :roles
  	root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dependecy.rb
class Dependecy < ApplicationRecord
	audited
end

app/models/permission.rb
class Permission < ApplicationRecord
	audited
end

app/models/permission_role.rb
class PermissionRole < ApplicationRecord
  belongs_to :permissions
  belongs_to :role
  audited
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :typerequest
  belongs_to :state
  audited
  attribute :state_id, :integer, default: '1'

  has_attached_file :cover
  validates_attachment_content_type :cover, content_type: [
	"application/pdf", "application/msword", 
	"application/vnd.openxmlformats-officedocument.wordprocessingml.document", 
	"application/vnd.oasis.opendocument.text",
	"application/vnd.ms-excel",
	"application/vnd.ms-office",
	"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	"application/vnd.oasis.opendocument.spreadsheet"
   ]
end

app/models/role.rb
class Role < ApplicationRecord
	audited
end

app/models/state.rb
class State < ApplicationRecord
	audited
end

app/models/typerequest.rb
class Typerequest < ApplicationRecord
	audited
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  audited
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  belongs_to :user
  belongs_to :role
  audited
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:nombre_solicitante, :apellido_solicitante, :email, :telefono, :direccion_solicitante, :typerequest_id, :detalles, :state_id, :cover)
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:nombre, :descripcion, :dependencie_id)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:nombre, :descripcion)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

 def index
    @usuarios = Usuario.all
  end
  
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dependecies_helper.rb
module DependeciesHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/typerequests_helper.rb
module TyperequestsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/requests/_form.html.erb
<div id="container">
      <div class="row center-xs">
        <div class="col-xs-8 col-md-6">
          <div class="box text-left">
            
            <%= form_with(model: request, local: true) do |form| %>
              <% if request.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>
            
                  <ul>
                  <% request.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
            
              <div class="field">
                <%= form.label :nombre_solicitante %>
                <%= form.text_field :nombre_solicitante, class:"form-control" %>
              </div>
            
              <div class="field">
                <%= form.label :apellido_solicitante %>
                <%= form.text_field :apellido_solicitante, class:"form-control" %>
              </div>
            
              <div class="field">
                <%= form.label :email %>
                <%= form.text_field :email, class:"form-control" %>
              </div>
            
              <div class="field">
                <%= form.label :telefono %>
                <%= form.number_field :telefono, class:"form-control" %>
              </div>
            
              <div class="field">
                <%= form.label :direccion_solicitante %>
                <%= form.text_field :direccion_solicitante, class:"form-control" %>
              </div>
            
              <div class="field">
                <%= form.label :typerequest_id %>
                <%= form.text_field :typerequest_id, class:"form-control" %>
              </div>
            
              <div class="field">
                <%= form.label :detalles %>
                <%= form.text_area :detalles, class:"form-control" %>
              </div>
            
              <div class="field">
             
               <%=label_tag "documento","Adjuntar documento (Solo *.pdf, *.xlsx, *.word *.jpg)"%>
                <%= form.file_field :cover %>
             
              </div>
            
              <div class="actions">
                <%= form.submit %>
              </div>
            <% end %>
        </div>
      </div>
  </div>
</div>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de PQR</h1>
<table class="table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Email</th>
      <th>Telefono</th>
      <th>Direccion</th>
      <th>Tipo de solicitud</th>
      <th>Detalles</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.nombre_solicitante %></td>
        <td><%= request.apellido_solicitante %></td>
        <td><%= request.email %></td>
        <td><%= request.telefono %></td>
        <td><%= request.direccion_solicitante %></td>
        <td><%= request.typerequest.nombre %></td>
        <td><%= request.detalles %></td>
        <td><%= link_to 'Show', request , class:"btn btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--%= link_to 'Nuevo PQR', new_request_path, class:"btn btn-default" %>>-->
<%= link_to 'Atras', root_path, class:"btn btn-default" %> 

app/views/requests/new.html.erb
<h1>Nuevo PQR</h1>

<%= render 'form', request: @request %>

<%= link_to 'Atras', root_path, class:"btn btn-default" %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre solicitante:</strong>
  <%= @request.nombre_solicitante %>
</p>

<p>
  <strong>Apellido solicitante:</strong>
  <%= @request.apellido_solicitante %>
</p>

<p>
  <strong>Email:</strong>
  <%= @request.email %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @request.telefono %>
</p>

<p>
  <strong>Direccion solicitante:</strong>
  <%= @request.direccion_solicitante %>
</p>

<p>
  <strong>Typerequest:</strong>
  <%= @request.typerequest %>
</p>

<p>
  <strong>Detalles:</strong>
  <%= @request.detalles %>
</p>

<p>
  <strong>State:</strong>
  <%= @request.state %>
</p>

<p>
  <strong>Archivo:</strong>
  <%= @request.cover %>
</p>

<%= link_to 'Editar', edit_request_path(@request),class:"btn btn-default" %> |
<%= link_to 'Atras', requests_path,class:"btn btn-default" %>

app/views/roles/_form.html.erb
<%= form_with(model: role, local: true) do |form| %>
  <% if role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div id="container">
      <div class="col-xs-8 col-md-6">
        <div class="field">
          <%= form.label :nombre %>
          <%= form.text_field :nombre, class:"form-control" %>
        </div>
      
        <div class="field">
          <%= form.label :descripcion %>
          <%= form.text_area :descripcion, class:"form-control" %>
        </div>

        <div class="field">
          <%= form.label :dependencie_id %>
          <%= form.text_area :dependencie_id, class:"form-control" %>
        </div>
      
      
        <div class="actions">
          <%= form.submit %>
        </div>
    </div>
  </div>
</div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editar Roles</h1>

<%= render 'form', role: @role %>

app/views/roles/index.html.erb
<h1>Roles</h1><br>

<%= link_to 'New Role', new_role_path, class:"btn btn-default" %>
<%= link_to 'Atras', root_path, class:"btn btn-default" %> 

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Dependencia</th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.nombre %></td>
        <td><%= role.descripcion %></td>
        <td><%= role.dependencie_id%></td>
        <td><%= link_to 'Edit', edit_role_path(role), class:"btn btn-default" %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/roles/new.html.erb
<h1>Crear Rol</h1>

<%= render 'form', role: @role %>

<%= link_to 'Back', roles_path, class:"btn btn-default" %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Mostrar</h1>
<br>
<div class = "container">
<table class="table table-bordered">
    <tr>
      <td>Nombre</td>
      <td><%= @role.nombre %></td>
    </tr>
    <tr>
      <td>Descripcion</td>
      <td><%= @role.descripcion %></td>
    </tr>
    <tr>
      <td>Dependencia</td>
      <td><%= @role.dependencie_id%></td>
    </tr>
</table>
</div>

<%= link_to 'Edit', edit_role_path(@role), class:"btn btn-default" %> |
<%= link_to 'Atras', roles_path, class:"btn btn-default" %>

app/views/states/_form.html.erb
<%= form_with(model: state, local: true) do |form| %>
  <% if state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<p id="notice"><%= notice %></p>

<h1>States</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.nombre %></td>
        <td><%= state.descripcion %></td>
        <td><%= link_to 'Show', state %></td>
        <td><%= link_to 'Edit', edit_state_path(state) %></td>
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @state.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @state.descripcion %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>